@startuml ACTIVITY_DIAGRAM_ADMIN_LIHATJADWAL
title Activity Diagram - Admin Lihat Jadwal Donor Darah

|Admin|
start
:Mengakses menu Jadwal Donor;

|Sistem|
:Mengambil data jadwal dari database;
:Menampilkan daftar jadwal donor;

|Admin|
:Melihat daftar jadwal donor;
stop

@enduml