@startuml ACTIVITY_DIAGRAM_ADMIN_TAMBAHJADWAL
title Activity Diagram - Admin Tambah Jadwal Donor Darah

|Admin|
start
:Memilih menu Jadwal Donor;
:Memilih opsi Tambah Jadwal;

|Sistem|
:Menampilkan form tambah jadwal;

|Admin|
:Mengisi form data jadwal baru;
:Menekan tombol Simpan;

|Sistem|
if (Data valid?) then (Ya)
  :Menyimpan data jadwal ;
  :Menampilkan pesan sukses;
else (Tidak)
  :Menampilkan error message;
endif

|Admin|
stop

@enduml