@startuml ACTIVITY_DIAGRAM_ADMIN_LIHATJADWAL
title Activity Diagram - Admin Lihat Jadwal Donor Darah

|Admin|
start
:Login dan masuk ke Dashboard;
:Klik menu "Jadwal Donor";

|Sistem|
:Kirim request untuk mengambil data jadwal;
:Terima balasan data jadwal terbaru;
:Tampilkan data dalam bentuk tabel interaktif;

|Admin|
:Melihat daftar jadwal donor;
stop

@enduml