@startuml ACTIVITY_DIAGRAM_ADMIN_LOGOUT
title Activity Diagram - Admin Logout

|Admin|
start
:Klik tombol "Keluar" di Sidebar;

|Sistem|
:Terima permintaan logout;
:Hapus session dan token autentikasi;
:Redirect ke halaman login;

|Admin|
:Melihat halaman login;
stop

@enduml