@startuml ACTIVITY_DIAGRAM_ADMIN_EDIT_BERITA
title Activity Diagram - Admin Edit Berita

|Admin|
start
:Buka menu Berita;
:Klik ikon "Lihat" (Mata);

|Sistem|
:Tampilkan form edit berita;

|Admin|
:Ubah data berita;
:Klik "Simpan Perubahan";

|Sistem|
:Validasi data;

if (Data valid?) then (Ya)
    :Simpan perubahan data berita;
    :Tampilkan notifikasi
    "Berita berhasil diperbarui";
    :Tampilkan data terbaru;
else (Tidak)
    :Tampilkan pesan error validasi;
endif

stop
@enduml