@startuml ACTIVITY_DIAGRAM_ADMIN_HAPUS_BERITA
title Activity Diagram - Admin Hapus Berita

|Admin|
start
:Buka menu Berita;
:Klik ikon "Hapus";

|Sistem|
:Tampilkan dialog konfirmasi penghapusan;

|Admin|
if (Yakin hapus?) then (Ya)
    :Klik "Hapus";

    |Sistem|
    :Hapus data berita;
    :Tampilkan notifikasi
    "Berita berhasil dihapus";
    :Perbarui daftar berita;

else (Tidak)
    :Klik "Batal";
endif

stop
@enduml