@startuml ACTIVITY_DIAGRAM_ADMIN_HAPUS_PESAN
title Activity Diagram - Admin Hapus Pesan

|Admin|
start
:Akses Pesan Masuk;
:Pilih Hapus;

|Sistem|
:Minta konfirmasi;

|Admin|
:Konfirmasi hapus;

|Sistem|
:Hapus data;
:Tampilkan notifikasi sukses;

|Admin|
stop
@enduml