@startuml ACTIVITY_DIAGRAM_USER_VIEW_DONASI
title Activity Diagram - Melakukan Donasi

|User|
start
:Akses halaman Donasi;

|Sistem|
:Tampilkan halaman Donasi;

|User|
if (Pilih jenis donasi?) then (Donasi Barang)

    :Pilih Hubungi Markas;

    |Sistem|
    :Arahkan ke halaman Kontak;

    |User|
    stop

else (Donasi Uang)

    :Isi form donasi uang;
    :Lanjut ke Pembayaran QRIS;

    |Sistem|
    :Buat data donasi awal;
    :Tampilkan kode QRIS;

    |User|
    :Transfer dana;

    repeat

        :Unggah bukti transfer;
        :Konfirmasi Pembayaran;

        |Sistem|
        :Validasi bukti;

        |User|
    repeat while (Valid?) is (Tidak)
    ->Ya;

    |Sistem|
    :Perbarui status donasi;
    :Tampilkan notifikasi sukses;

    |User|
    :Kembali ke Beranda;

    |Sistem|
    :Arahkan ke Beranda;

    |User|
    stop

endif
@enduml