@startuml ACTIVITY_DIAGRAM_ADMIN_EDIT_INFOGRAFIS
title Activity Diagram - Admin Edit Infografis

|Admin|
start
:Akses menu Infografis;
:Pilih Edit;

|Sistem|
:Ambil data;
:Tampilkan form edit;

|Admin|
:Ubah data;
:Simpan Perubahan;

|Sistem|
:Validasi input;
if (Valid?) then (Ya)
  |Sistem|
  :Update data;
  :Tampilkan notifikasi sukses;
else (Tidak)
  |Sistem|
  :Tampilkan galat;
endif

|Admin|
stop
@enduml
