@startuml ACTIVITY_DIAGRAM_ADMIN_MANAGE_PESAN
title Activity Diagram - Kelola Pesan

|Admin|
start
:Akses Pesan Masuk;

|Sistem|
:Ambil data;

|Database|
:Ambil pesan;

|Sistem|
:Tampilkan pesan;

|Admin|
:Pilih pesan;
if (Aksi?) then (Balas)
  :Tulis balasan;
  |Sistem|
  :Validasi;
  |Database|
  if (Valid?) then (Ya)
    :Simpan balasan;
  else (Tidak)
    |Sistem|
    :Tampilkan galat;
    stop
  endif
else (Hapus)
  |Admin|
  :Konfirmasi Hapus;
  |Database|
  :Hapus pesan;
endif

|Sistem|
:Tampilkan notifikasi sukses;

stop
@enduml
