@startuml ACTIVITY_DIAGRAM_ADMIN_BALAS_PESAN
title Activity Diagram - Admin Balas Pesan

|Admin|
start
:Buka menu Pesan Masuk;
:Pilih salah satu pesan;

|Sistem|
:Tampilkan detail pesan;

|Admin|
:Ketik isi balasan;

if (Pilih metode balasan?) then (Email)

    :Klik "Balas via Email";

    |Sistem|
    :Kirim balasan melalui Email;
    :Tampilkan notifikasi
    "Balasan berhasil dikirim";

else (WhatsApp)

    :Klik "Balas via WhatsApp";

    |Sistem|
    :Kirim balasan melalui WhatsApp;
    :Tampilkan notifikasi
    "Balasan berhasil dikirim";

endif


stop
@enduml