@startuml ACTIVITY_DIAGRAM_USER_BERANDA
title Activity Diagram - User Beranda

|User|
start
:Akses halaman Beranda;

|Sistem|
:Ambil data infografis;
:Tampilkan halaman Beranda;

|User|
:Lihat menu navigasi;

if (Pilih menu?) 

    :Pilih menu yang dituju;

    |Sistem|
    :Tampilkan halaman yang dipilih;

else ()

    |User|
    :Pilih bulan laporan;

    |Sistem|
    :Perbarui tampilan data;

endif

|User|
stop
@enduml