@startuml ACTIVITY_DIAGRAM_ADMIN_BALAS_PESAN
title Activity Diagram - Admin Balas Pesan

|Admin|
start
:Akses Pesan Masuk;
:Pilih pesan;

|Sistem|
:Tampilkan detail;

|Admin|
:Tulis balasan;
:Pilih metode (Email/WhatsApp);

|Sistem|
:Kirim balasan;
:Tampilkan notifikasi sukses;

|Admin|
stop
@enduml