@startuml ACTIVITY_DIAGRAM_ADMIN_HAPUS_INFOGRAFIS
title Activity Diagram - Admin Hapus Infografis

|Admin|
start
:Akses menu Infografis;
:Pilih Hapus;

|Sistem|
:Minta konfirmasi;

|Admin|
if (Konfirmasi?) then (Ya)
  |Sistem|
  :Hapus data;
  :Tampilkan notifikasi sukses;
else (Tidak)
endif

|Admin|
stop
@enduml
