@startuml ACTIVITY_DIAGRAM_ADMIN_LOGOUT
title Activity Diagram - Admin Logout

|Admin|
start
:Mengklik tombol "Keluar" pada sidebar;

|Sistem|
:Menampilkan validasi konfirmasi logout;

|Admin|
if (Konfirmasi keluar?) then (Tidak)
  :Kembali ke halaman sebelumnya;
  stop
else (Ya)
  |Sistem|
  :Menerima permintaan logout;
  :Menghapus session dan token autentikasi;
  :Redirect ke halaman login;
  
  |Admin|
  :Melihat halaman login;
  stop
endif

@enduml