@startuml ACTIVITY_DIAGRAM_USER_VIEW_INFO_DONOR
title Activity Diagram - Lihat Info Donor

|User|
start
:Akses halaman Info Donor;

|Sistem|
:Tampilkan halaman Info Donor;

|User|
:Baca panduan dan prosedur donor;

if (Pilih aksi?) then (Hubungi PMI)

    :Klik tombol Hubungi PMI;

    |Sistem|
    :Arahkan ke halaman Kontak;

    |User|
    :Lihat halaman Kontak;

else (Hanya Lihat)

endif

|User|
stop
@enduml