@startuml ACTIVITY_DIAGRAM_ADMIN_TAMBAH_INFOGRAFIS
title Activity Diagram - Tambah Infografis

|Admin|
start
:Akses menu Infografis;

|Sistem|
:Tampilkan form;

|Admin|
:Isi info umum (bulan/tahun);
:Isi kontak & statistik;
:Upload dokumentasi;
:Isi kata motivasi;
:Simpan Semua;

|Sistem|
:Validasi input;
if (Valid?) then (Ya)
  |Database|
  :Simpan data;
  |Sistem|
  :Tampilkan notifikasi sukses;
else (Tidak)
  |Sistem|
  :Tampilkan galat;
endif

|Admin|
stop
@enduml