@startuml ACTIVITY_DIAGRAM_ADMIN_LIHAT_BUKTI_DONASI
title Activity Diagram - Admin Lihat Bukti Transfer Donasi

|Admin|
start
:Buka menu Donasi Masuk;
:Klik tombol "Lihat Bukti" pada salah satu donasi;

|Sistem|
:Ambil URL/file gambar bukti transfer;
:Tampilkan gambar bukti transfer\ndi dalam Modal (Pop-up);

|Admin|
:Melihat gambar bukti transfer;
:Klik tombol "Tutup" ;

|Sistem|
:Tutup;

|Admin|
stop

@enduml
