@startuml ACTIVITY_DIAGRAM_USER_VIEW_BERITA
title Activity Diagram - Lihat Berita

|User|
start
:Akses halaman Berita;

|Sistem|
:Ambil data berita;
:Tampilkan halaman Berita;

|User|
:Lihat daftar berita;

if (Pilih aksi?) then (Baca Selengkapnya)
    |Sistem|
    :Tampilkan pop-up detail berita;
    |User|
    :Baca isi berita;
    :Tutup pop-up detail;
    |Sistem|
    :Sembunyikan pop-up berita;
else (Hanya Lihat)
endif

|User|
stop
@enduml