@startuml ACTIVITY_DIAGRAM_ADMIN_LIHAT_PESAN
title Activity Diagram - Admin Lihat Pesan

|Admin|
start
:Pilih Pesan Masuk;

|Sistem|
:Tampilkan daftar pesan;

|Admin|
:Pilih pesan;

|Sistem|
:Tampilkan detail pesan;

stop
@enduml
