@startuml ACTIVITY_DIAGRAM_ADMIN_LOGIN
title Activity Diagram - Admin Login

|Admin|
start
:Mengakses halaman login admin (/admin/login);
:Memasukkan username dan password;

|Sistem|
:Menerima data formulir login;
:Melakukan validasi (memeriksa database & memverifikasi password);

if (Validasi berhasil?) then (Ya)
  :Membuat session pengguna;
  :Mengatur token autentikasi;
else (Tidak)
  :Menampilkan pesan kesalahan;
  stop
endif

|Admin|
:Redirect ke halaman dashboard;
stop

@enduml